puts "#5\nThe first program puts 3, and there are no errors\n
The second program returns an error because x was created inside the method, and isn't
accessible outside that scope. Within that method, x takes on the value of y, which is 3."
